[package]
name = "discord-tui"
version = "0.1.0"
edition = "2024"
authors = ["retr0", "kowkodivka"]
license = "MIT"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
<<<<<<< HEAD
=======
tokio = { version = "*", features = ["full"] }
reqwest = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
secrecy = "0.10.3"
>>>>>>> refs/remotes/origin/master
