[package]
name = "discord-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
tokio = { version = "*", features = ["full"] }
reqwest = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
secrecy = "0.10.3"
